### ISSUE TITLE
Example image data not appropriately obfuscated

### ISSUE THREAD

**Issue by professorhantzen** [filidorwiese/ripple-wallet#22]
It would be possible to figure out the secret from the information provided. The supplied public/private key pair should not be considered safe for holding funds. Also, if the intention in masking the public addresses is to maintain privacy, the provided portions are readily grep-able within any ledgers accountState to reveal the full address. (Information also useful in unmasking the secret.)

I would attempt to convey this information privately, but the repository has already been forked several times.  (A safer way to provide examples might be to paste over the real addresses with dummy/unused accounts or random values, prior to taking a screenshot.)

**Comment by Ponderjaunt** [comment]
I'm very glad someone brought this up, I had the same concerns aftering
viewing the git; it would be very easy to brute the remaining characters of
the public wallet I'd and PK based on that photo.

On Jun 30, 2018 11:24 AM, "professorhantzen" <notifications@github.com>
wrote:

It would be possible to figure out the secret from the information
provided. The supplied public/private key pair should not be considered
safe for holding funds. Also, if the intention in masking the public
addresses is to maintain privacy, the provided portions are readily
grep-able within any ledgers accountState to reveal the full address.
(Information also useful in unmasking the secret.)

I would attempt to convey this information privately, but the repository
has already been forked several times. (A safer way to provide examples
might be to paste over the real addresses with dummy/unused accounts or
random values, prior to taking a screenshot.)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/filidorwiese/ripple-wallet/issues/22>, or mute the
thread

**Comment by filidorwiese** [comment]
Thanks for your concern. The account mentioned in the image is actually dummy. The obfuscation in the image was to illustratie the fact that the private key should be secret. I'll make a new version of the image to make that more clear.
